minecraft_blocks = [
    "minecraft:air",
    "minecraft:oak_planks",
    "minecraft:spruce_planks",
    "minecraft:birch_planks",
    "minecraft:jungle_planks",
    "minecraft:acacia_planks",
    "minecraft:dark_oak_planks",
    "minecraft:mangrove_planks",
    "minecraft:crimson_planks",
    "minecraft:stone",
    "minecraft:cobblestone",
    "minecraft:mossy_cobblestone",
    "minecraft:smooth_stone",
    "minecraft:stone_bricks",
    "minecraft:mossy_stone_bricks",
    "minecraft:granite",
    "minecraft:polished_granite",
    "minecraft:diorite",
    "minecraft:polished_diorite",
    "minecraft:andesite",
    "minecraft:polished_andesite",
    "minecraft:deepslate",
    "minecraft:cobbled_deepslate",
    "minecraft:chiseled_deepslate",
    "minecraft:polished_deepslate",
    "minecraft:deepslate_bricks",
    "minecraft:cracked_deepslate_bricks",
    "minecraft:deepslate_tiles",
    "minecraft:cracked_deepslate_tiles",
    "minecraft:reinforced_deepslate",
    "minecraft:bricks",
    "minecraft:packed_mud",
    "minecraft:oak_log",
    "minecraft:spruce_log",
    "minecraft:birch_log",
    "minecraft:jungle_log",
    "minecraft:acacia_log",
    "minecraft:dark_oak_log",
    "minecraft:mangrove_log",
    "minecraft:crimson_stem",
    "minecraft:stripped_oak_log",
    "minecraft:stripped_spruce_log",
    "minecraft:stripped_birch_log",
    "minecraft:stripped_jungle_log",
    "minecraft:stripped_acacia_log",
    "minecraft:stripped_dark_oak_log",
    "minecraft:stripped_mangrove_log",
    "minecraft:stripped_crimson_stem",
    "minecraft:white_wool",
    "minecraft:orange_wool",
    "minecraft:magenta_wool",
    "minecraft:light_blue_wool",
    "minecraft:yellow_wool",
    "minecraft:lime_wool",
    "minecraft:pink_wool",
    "minecraft:gray_wool",
    "minecraft:light_gray_wool",
    "minecraft:cyan_wool",
    "minecraft:purple_wool",
    "minecraft:blue_wool",
    "minecraft:brown_wool",
    "minecraft:green_wool",
    "minecraft:red_wool",
    "minecraft:black_wool",
    "minecraft:white_concrete",
    "minecraft:orange_concrete",
    "minecraft:magenta_concrete",
    "minecraft:light_blue_concrete",
    "minecraft:yellow_concrete",
    "minecraft:lime_concrete",
    "minecraft:pink_concrete",
    "minecraft:gray_concrete",
    "minecraft:light_gray_concrete",
    "minecraft:cyan_concrete",
    "minecraft:purple_concrete",
    "minecraft:blue_concrete",
    "minecraft:brown_concrete",
    "minecraft:green_concrete",
    "minecraft:red_concrete",
    "minecraft:black_concrete",
    "minecraft:white_glazed_terracotta",
    "minecraft:orange_glazed_terracotta",
    "minecraft:magenta_glazed_terracotta",
    "minecraft:light_blue_glazed_terracotta",
    "minecraft:yellow_glazed_terracotta",
    "minecraft:lime_glazed_terracotta",
    "minecraft:pink_glazed_terracotta",
    "minecraft:gray_glazed_terracotta",
    "minecraft:light_gray_glazed_terracotta",
    "minecraft:cyan_glazed_terracotta",
    "minecraft:purple_glazed_terracotta",
    "minecraft:blue_glazed_terracotta",
    "minecraft:brown_glazed_terracotta",
    "minecraft:green_glazed_terracotta",
    "minecraft:red_glazed_terracotta",
    "minecraft:black_glazed_terracotta",
    "minecraft:white_stained_glass",
    "minecraft:orange_stained_glass",
    "minecraft:magenta_stained_glass",
    "minecraft:light_blue_stained_glass",
    "minecraft:yellow_stained_glass",
    "minecraft:lime_stained_glass",
    "minecraft:pink_stained_glass",
    "minecraft:gray_stained_glass",
    "minecraft:light_gray_stained_glass",
    "minecraft:cyan_stained_glass",
    "minecraft:purple_stained_glass",
    "minecraft:blue_stained_glass",
    "minecraft:brown_stained_glass",
    "minecraft:green_stained_glass",
    "minecraft:red_stained_glass",
    "minecraft:black_stained_glass",
    "minecraft:white_terracotta",
    "minecraft:orange_terracotta",
    "minecraft:magenta_terracotta",
    "minecraft:light_blue_terracotta",
    "minecraft:yellow_terracotta",
    "minecraft:lime_terracotta",
    "minecraft:pink_terracotta",
    "minecraft:gray_terracotta",
    "minecraft:light_gray_terracotta",
    "minecraft:cyan_terracotta",
    "minecraft:purple_terracotta",
    "minecraft:blue_terracotta",
    "minecraft:brown_terracotta",
    "minecraft:green_terracotta",
    "minecraft:red_terracotta",
    "minecraft:black_terracotta",
    "minecraft:warped_stem",
    "minecraft:stripped_warped_stem",
    "minecraft:warped_planks",
    "minecraft:mud_bricks",
    "minecraft:wet_sponge",
    "minecraft:melon",
    "minecraft:mushroom_stem",
    "minecraft:pumpkin",
    "minecraft:hay_block",
    "minecraft:bee_nest",
    "minecraft:sponge",
    "minecraft:honeycomb_block",
    "minecraft:sea_lantern",
    "minecraft:prismarine",
    "minecraft:prismarine_bricks",
    "minecraft:dark_prismarine",
    "minecraft:netherrack",
    "minecraft:nether_bricks",
    "minecraft:cracked_nether_bricks",
    "minecraft:chiseled_nether_bricks",
    "minecraft:red_nether_bricks",
    "minecraft:basalt",
    "minecraft:smooth_basalt",
    "minecraft:polished_basalt",
    "minecraft:pearlescent_froglight",
    "minecraft:gilded_blackstone",
    "minecraft:chiseled_polished_blackstone",
    "minecraft:polished_blackstone",
    "minecraft:polished_blackstone_bricks",
    "minecraft:cracked_polished_blackstone_bricks",
    "minecraft:end_stone",
    "minecraft:end_stone_bricks",
    "minecraft:purpur_block",
    "minecraft:purpur_pillar",
    "minecraft:coal_block",
    "minecraft:iron_block",
    "minecraft:gold_block",
    "minecraft:chiseled_stone_bricks",
    "minecraft:emerald_block",
    "minecraft:lapis_block",
    "minecraft:diamond_block",
    "minecraft:netherite_block",
    "minecraft:quartz_block",
    "minecraft:chiseled_quartz_block",
    "minecraft:quartz_bricks",
    "minecraft:quartz_pillar",
    "minecraft:muddy_mangrove_roots",
    "minecraft:target",
    "minecraft:oxidized_copper",
    "minecraft:oxidized_cut_copper",
    "minecraft:waxed_copper_block",
    "minecraft:waxed_cut_copper",
    "minecraft:waxed_exposed_copper",
    "minecraft:waxed_exposed_cut_copper",
    "minecraft:waxed_weathered_copper",
    "minecraft:waxed_weathered_cut_copper",
    "minecraft:waxed_oxidized_copper",
    "minecraft:waxed_oxidized_cut_copper",
    "minecraft:dried_kelp_block",
    "minecraft:dead_tube_coral_block",
    "minecraft:dead_brain_coral_block",
    "minecraft:dead_bubble_coral_block",
    "minecraft:dead_fire_coral_block",
    "minecraft:dead_horn_coral_block",
    "minecraft:grass_block",
    "minecraft:podzol",
    "minecraft:mycelium",
    "minecraft:dirt",
    "minecraft:coarse_dirt",
    "minecraft:rooted_dirt",
    "minecraft:mud",
    "minecraft:clay",
    "minecraft:spawner",
    "minecraft:honey_block",
    "minecraft:ice",
    "minecraft:packed_ice",
    "minecraft:blue_ice",
    "minecraft:snow_block",
    "minecraft:moss_block",
    "minecraft:calcite",
    "minecraft:tuff",
    "minecraft:dripstone_block",
    "minecraft:terracotta",
    "minecraft:magma_block",
    "minecraft:obsidian",
    "minecraft:crying_obsidian",
    "minecraft:glass",
    "minecraft:crimson_nylium",
    "minecraft:warped_nylium",
    "minecraft:soul_sand",
    "minecraft:soul_soil",
    "minecraft:bone_block",
    "minecraft:tinted_glass",
    "minecraft:ochre_froglight",
    "minecraft:verdant_froglight",
    "minecraft:slime_block",
    "minecraft:coal_ore",
    "minecraft:deepslate_coal_ore",
    "minecraft:iron_ore",
    "minecraft:deepslate_iron_ore",
    "minecraft:copper_ore",
    "minecraft:deepslate_copper_ore",
    "minecraft:gold_ore",
    "minecraft:deepslate_gold_ore",
    "minecraft:redstone_ore",
    "minecraft:deepslate_redstone_ore",
    "minecraft:emerald_ore",
    "minecraft:deepslate_emerald_ore",
    "minecraft:lapis_ore",
    "minecraft:deepslate_lapis_ore",
    "minecraft:diamond_ore",
    "minecraft:deepslate_diamond_ore",
    "minecraft:nether_gold_ore",
    "minecraft:nether_quartz_ore",
    "minecraft:ancient_debris",
    "minecraft:raw_iron_block",
    "minecraft:raw_copper_block",
    "minecraft:raw_gold_block",
    "minecraft:glowstone",
    "minecraft:amethyst_block",
    "minecraft:budding_amethyst",
    "minecraft:note_block",
    "minecraft:brown_mushroom_block",
    "minecraft:red_mushroom_block",
    "minecraft:nether_wart_block",
    "minecraft:warped_wart_block",
    "minecraft:shroomlight",
    "minecraft:redstone_lamp"
]

def convert_address_to_xyz(address):
    origin = [0, 0, 0]
    x = (3 - (address % 4) + (address // 4) * 4 + origin[0]) % 4096
    y = address // (4096 * 4096) + origin[1]
    z = address // 4096 + origin[2]
    return x, y, -z

with open("output_dump.txt", 'r') as f:
    lines = f.readlines()
    lines = ["".join(line.strip().split("|")[0].split(" ")[1:]) for line in lines]
    program = "".join(lines)
    

if len(program) % 2 != 0:
    raise Exception("Invalid length of data")

if any([int(program[i:i+2], 16) >= len(minecraft_blocks) for i in range(0, len(program), 2)]):
    raise Exception("Invalid block in data")

address = 0
with open(r"Computer\data\computer\function\program.mcfunction", 'w') as f:
    for i in range(0, len(program), 2):
        block = int(program[i:i+2], 16)
        x,y,z = convert_address_to_xyz(address)
        if block >= len(minecraft_blocks):
            raise Exception(f"Invalid block {block} at address {address}")
        f.write(f"setblock {x} {y} {z} {minecraft_blocks[block]}\n")
        address += 1

print("Done")